name: CI-CD

on: [push,pull_request]

jobs:
  test:
    name: CI-CD from ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter pub get
      - run: flutter format .
      - run: flutter analyze
      - run: flutter config --enable-linux-desktop
      - run: flutter test --dart-define="site_url=${{ secrets.site_url }}" --dart-define="token_auth=${{ secrets.token_auth }}" --dart-define="idsite=${{ secrets.idsite }}" --dart-define="action_name=${{ secrets.action_name }}"
      - run: pushd example&&flutter build linux&&flutter build web
      - name: Archive Linux Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'matomo_forever_example.zip'
          path: 'example/build/linux/x64/release/bundle/'
      - name: Upload linux to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "matomo_forever_example.zip"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Upload web to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "example/build/web"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
