name: CI-CD

on: [push,pull_request]

jobs:
#  linux:
#    name: CI-CD from ${{ matrix.os }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-latest]
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '12.x'
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: 'dev'
#      - run: flutter pub get
#
#      - run: mkdir -p docs
#      - run: rm -rf docs/*
#
#      - run: flutter format .
#      - run: flutter analyze
#      - run: flutter test --dart-define="site_url=${{ secrets.site_url }}" --dart-define="token_auth=${{ secrets.token_auth }}" --dart-define="idsite=${{ secrets.idsite }}" --dart-define="action_name=${{ secrets.action_name }}"
#
#      - run: pushd example&&flutter build apk --release
#      - run: mv example/build/app/outputs/flutter-apk/app-release.apk docs/matomo_forever_example_android.apk
#
#      - run: flutter config --enable-linux-desktop
#      - name: Installations for linux build
#        run: |
#          sudo apt-get update -y
#          sudo apt-get install -y clang ninja-build libgtk-3-dev
#      - run: pushd example&&flutter build linux --release
#      - name: Archive Linux Release
#        uses: thedoctor0/zip-release@master
#        with:
#          type: 'zip'
#          filename: 'docs/matomo_forever_example_linux.zip'
#          path: 'example/build/linux/x64/release/bundle/'
#
#      - run: pushd example&&flutter build web --web-renderer canvaskit --release
#      - name: Archive web Release
#        uses: thedoctor0/zip-release@master
#        with:
#          type: 'zip'
#          filename: 'docs/matomo_forever_example_web.zip'
#          path: 'example/build/web/'
#      - run: cp -r example/build/web/* docs/
#      - run: sed -i 's/<base href="\/">/<base href="\/matomo_forever\/">/g' docs/index.html
#
#      -
#        name: Deploy to GitHub Pages
#        if: success()
#        uses: crazy-max/ghaction-github-pages@v2
#        with:
#          build_dir: docs
#          jekyll: false
#          keep_history: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'

#      - run: flutter upgrade
#      - run: flutter pub get
#      #- run: sed -i '' -e "s/# platform :ios, '9\.0'/platform :ios, '12\.0'/" example/ios/Podfile
#      - run: pushd example&&flutter create .
#      - run: pushd example&&flutter pub get
#      - run: pushd example&&flutter build ios --release --no-codesign

      - run: pushd example&&flutter config --enable-macos-desktop
      - run: pushd example&&flutter create .
      - run: pushd example&&flutter pub get
      - run: sed -i '' -e "s/<\/dict>/<key>com\.apple\.security\.network\.client<\/key><true\/><\/dict>/" example/macos/Runner/DebugProfile.entitlements
      - run: sed -i '' -e "s/<\/dict>/<key>com\.apple\.security\.network\.client<\/key><true\/><\/dict>/" example/macos/Runner/Release.entitlements
      - run: pushd example&&flutter build macos --release
      - run: mkdir -p docs
      - run: rm -rf docs/*
      - name: Archive ios and mac Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'docs/matomo_forever_example_macos.zip'
          path: 'example/build/macos/Build/Products/Release/'
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: docs
          jekyll: false
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

#  windows:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: beta
#      - run: pushd example&&flutter config --enable-windows-desktop
#      - run: pushd example&&flutter create .&&flutter build windows
#      - run: md docs
#      - name: Archive Windows Release
#        uses: thedoctor0/zip-release@master
#        with:
#          type: 'zip'
#          filename: 'docs/matomo_forever_example_windows.zip'
#          path: 'example/build/windows/runner/Release/'
#      -
#        name: Deploy to GitHub Pages
#        if: success()
#        uses: crazy-max/ghaction-github-pages@v2
#        with:
#          build_dir: docs
#          jekyll: false
#          keep_history: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
