name: CI-CD

on: [push,pull_request]

jobs:
  test:
    name: CI-CD from ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter pub get
#      - run: flutter format .
#      - run: flutter analyze
#      - run: flutter config --enable-linux-desktop
#      - run: flutter test --dart-define="site_url=${{ secrets.site_url }}" --dart-define="token_auth=${{ secrets.token_auth }}" --dart-define="idsite=${{ secrets.idsite }}" --dart-define="action_name=${{ secrets.action_name }}"
#      - name: Installations for linux build
#        run: |
#          sudo apt-get update -y
#          sudo apt-get install -y clang ninja-build libgtk-3-dev
#      - run: pushd example&&flutter build linux
      - run: pushd example&&flutter build web
      - run: mkdir -p docs
      - run: rm -rf docs/*
      - run: cp -r example/build/web/* docs/
      - run: sed -i 's/main\.dart\.js/matomo_forever\/main\.dart\.js/g' docs/index.html
      - run: sed -i 's/flutter_service_worker/matomo_forever\/flutter_service_worker/g' docs/index.html
      - name: Archive Linux Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'docs/matomo_forever_example.zip'
          path: 'example/build/linux/x64/release/bundle/'
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
